apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: echo-server
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: terachanple/echo-server-go:latest
